name: Carousell once

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Run scraper
        run: npm test
      - name: Git commit listings
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          # branch: feature-123
          commit_message: commit listings.json
          file_pattern: 'data/listings.json'
